#31: Email rendering service api
ripe-tech/peri-templating-api-js pull request #1
Opened 2020-09-25 07:48 UTC by BeeMargarida

| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-registry/issues/31 |
| Dependencies | https://github.com/ripe-tech/peri-templating/pull/13 |
| Decisions | API for [`peri-templating` service](https://github.com/ripe-tech/peri-templating), more specifically the order's endpoint. |
| Animated GIF | -- |

2020-09-30 10:19 UTC, gcandal requested changes

2020-09-30 10:19 UTC, gcandal commented on js/base.js
> +const TEMPLATING_SERVICE_URL = "http://localhost:3000/";
Point to now instead

2020-09-30 10:19 UTC, gcandal commented on js/order.js
> +        async getOrderTemplate(event) {
If this is a templating API client then this can only be `getOrder`, otherwise we'll have `getXTemplate` everywhere.

2020-09-30 10:19 UTC, gcandal commented on types/order.d.ts
> +    getOrderTemplate(event: Object): Blob;
Blob or string?

2020-09-30 10:19 UTC, gcandal commented on js/order.js
> +            return await contents.text();
Please talk with @3rdvision about this

2020-09-30 11:17 UTC, gcandal approved these changes

2020-10-10 08:12 UTC, joamag requested changes

2020-10-10 08:12 UTC, joamag commented on .gitignore
> +example.env
let's remove this from ignore ;)

2020-10-10 08:12 UTC, joamag commented on js/base.js
> +        this.baseUrl = conf("TEMPLATING_SERVICE_URL", TEMPLATING_SERVICE_URL);
let's call this config variable `PERI_TEMPLATING_URL` and the constant `BASE_URL`

2020-10-10 08:12 UTC, joamag commented on js/base.js
> +        this.token = conf("TEMPLATING_SERVICE_TOKEN", null);
PERI_TEMPLATING_TOKEN

2020-10-10 08:17 UTC, joamag approved these changes

2020-10-10 08:17 UTC, merged