#31: Reviews endpoints
ripe-tech/peri-templating-api-js pull request #2
Opened 2020-10-02 08:47 UTC by BeeMargarida

| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-registry/issues/31 |
| Dependencies | • https://github.com/ripe-tech/peri-templating-api-js/pull/1 |
| Decisions | API for [`peri-templating` service](https://github.com/ripe-tech/peri-templating), more specifically the **reviews**. |
| Animated GIF | -- |

2020-10-02 16:05 UTC, gcandal requested changes

2020-10-02 16:05 UTC, gcandal commented on types/review.d.ts
> +}
Missing newline.

2020-10-02 16:47 UTC, gcandal approved these changes

2020-10-10 08:25 UTC, joamag commented
@gcandal @BeeMargarida check the renaming of the methods and notice that the name of API broker methods must always end with the name of the entity

2020-10-10 08:25 UTC, merged

2020-10-12 08:34 UTC, gcandal commented
> @gcandal @BeeMargarida check the renaming of the methods and notice that the name of API broker methods must always end with the name of the entity

@joamag even though it's a POST, that just happens because we need to pass a JSON as param. If it was not for that limitation, semantically it would be a GET (has no side effects), that's why we named it as `getX`.